# Generated by Django 3.2.25 on 2025-03-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=225)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Laboratory name', max_length=225)),
                ('city', models.ForeignKey(help_text='city id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='auto.city')),
            ],
            options={
                'db_table': 'laboratory',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Compute name', max_length=225)),
                ('host', models.CharField(help_text='Compute IP', max_length=225)),
                ('laboratory', models.ForeignKey(help_text='laboratory id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory', to='auto.laboratory')),
            ],
            options={
                'db_table': 'pc',
            },
        ),
    ]
